version: "3.5"

services:
  users-service:
    container_name: users-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: users-service
    ports:
      - "8082:8080"
    depends_on:
      - users-service_database
    networks:
      - noodlee-system-network

  users-service_database:
    container_name: users-service_database
    image: postgres:9.6
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3CcbvP@!z&YZ6Hkb3yp_
      POSTGRES_DB: users
    volumes:
      - users-service_database-volume:/var/lib/postgresql/users
    networks:
      - noodlee-system-network

networks:
  noodlee-system-network:
    name: noodlee-system-network
    driver: bridge
    
volumes:
  users-service_database-volume:
